// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoginPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><head><title>Login | Survivor Fantasy League</title><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><link rel=\"stylesheet\" href=\"/static/style.css\"></head><body><header><h1>Survivor Fantasy League</h1></header><main class=\"auth-page\"><section class=\"auth-card\"><h2>Log in</h2><p class=\"muted\">Sign in to manage your leagues and set your roster.</p><form class=\"auth-form\"><label for=\"email\">Email</label> <input id=\"email\" name=\"email\" type=\"email\" placeholder=\"you@example.com\" autocomplete=\"off\" required> <label for=\"password\">Password</label> <input id=\"password\" name=\"password\" type=\"password\" placeholder=\"Enter your password\" autocomplete=\"off\" required><div class=\"checkbox-row\"><input id=\"remember\" name=\"remember\" type=\"checkbox\"> <label for=\"remember\">Remember me</label></div><button type=\"submit\">Continue</button></form><p class=\"form-footer\">Need an account? <a href=\"#\">Create one</a></p></section></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
